# Generated by Django 6.0.3 on 2026-07-17 10:31

from django.db import migrations

# Starter categories for the pilot city (spec F2.2: admin-managed list).
# Admins can rename/recolor/deactivate these and add new ones in Django admin.
GAETA_CATEGORIES = (
    ('Strade e marciapiedi', '#ef4444'),
    ('Illuminazione pubblica', '#f59e0b'),
    ('Rifiuti e decoro', '#84cc16'),
    ('Verde pubblico', '#22c55e'),
    ('Acqua e fognature', '#06b6d4'),
    ('Arredo urbano', '#8b5cf6'),
    ('Altro', '#6b7280'),
)


def seed_categories(apps, schema_editor):
    Category = apps.get_model('reports', 'Category')
    for name, color in GAETA_CATEGORIES:
        Category.objects.get_or_create(name=name, defaults={'color': color})


def unseed_categories(apps, schema_editor):
    Category = apps.get_model('reports', 'Category')
    Category.objects.filter(
        name__in=[name for name, _ in GAETA_CATEGORIES], reports__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
