# Generated by Django 6.0.3 on 2026-07-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('post_like', 'Post like'), ('post_comment', 'Post comment')], max_length=50),
        ),
    ]
