# Generated by Django 6.0.3 on 2026-07-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts_count',
        ),
    ]
